### ISSUE TITLE
Výměna mazací ikony

### ISSUE THREAD

**Issue by j-jzk** [frenzymadness/donors_registry#113]
V mém prohlížeči se nezobrazují ikony koše 🗑 pro smazání záznamu nebo medaile, pravděpodobně kvůli chybějícímu znaku ve fontu. Po vypnutí `input { font-family: inherit; }` (bootstrap.css, ř. 236) z vývojářských nástrojů se ikona zobrazuje, ale na červeném pozadí je nevzhledná a špatně čitelná.

Navrhuji místo emoji koše použít jiný znak (✘, příp. [další](https://en.wikipedia.org/wiki/X_mark), které by snad měly mít širší podporu), nebo přejít na Font Awesome nebo něco podobného.

**Comment by Glutexo** [comment]
Na systémy nepodporující emotikony bych v roce 2021 vůbec nebral ohled.

**Comment by Glutexo** [comment]
Emotikony se mají vykreslovat nezávisle na řezu písma. Je úplně jedno, jestli je daný řez obsahuje, nebo ne. Standardní písma by je ani obsahovat neměla. Pokud _font-family_ jakkoliv ovlivňuje vykreslování emotikon, je to chyba prohlížeče/systému.

**Comment by j-jzk** [comment]
ok

**Comment by frenzymadness** [comment]
Já bych se ještě zeptal, co máš za systém a prohlížeč? To, že jsme identifikovali, kde chyba nejspíše je, neznamená, že nebude pro uživatele obtěžující.

**Comment by j-jzk** [comment]
Firefox/Debian 10. Chyba bude asi ve fontech, protože na VM s Win 7 a Firefoxem se koš zobrazuje.

**Comment by Glutexo** [comment]
Existuje [tahle příšernost](https://github.com/twitter/twemoji), co nahrazuje emočíky obrázky. Viděl jsem to použít na nějakém pyvčím projektu. Odstraní to chybné vykreslování a také rozdílnost napříč platformami. Přinese to další závislost a hromadu nečekaných potíží.

**Comment by frenzymadness** [comment]
Prozatím bych to uzavřel s tím, že o potencionálním problému pro některé uživatele víme a máme i nějaká možná řešení, ale v tuto chvíli nemá smysl je implementovat.
