### ISSUE TITLE
Lepší chybové hlášky u formulářů

### ISSUE THREAD

**Issue by j-jzk** [frenzymadness/donors_registry#115]
Při zadání špatných přihlašovacích údajů se zobrazí zpráva anglicky a v poněkud nešťastném formátu (_Email - Unknown email_ vypadá divně). 
Upravené zprávy jsem přidal [zde](https://github.com/j-jzk/donors_registry/tree/form-msg), ale žádným způsobem se mi nepodařilo nastavit locale, aby se zobrazovala česká zpráva u validátoru vybraného odběrového místa při importu (viz test test_invalid_donation_center). K podobné zprávě by se ale uživatel ani neměl dostat, takže by to snad neměl být velký problém (možná v budoucnu u jiných formulářů).
WDYT?

**Comment by adelpopelkova** [comment]
Já jsem určitě pro chybové hlášky v češtině.
Doporučila bych asi otevřít PR, protože tam bude možná trochu větší šance, že se na to nezapomene a bude motivace změny dokončit. :smile:

**Comment by frenzymadness** [comment]
Řešeno v rámci #160. JS hlášky se snad nějak překládají automaticky v HTML podle nastavení uživatele, ale ty generované na backendu by snad už měly být česky.
