### ISSUE TITLE
Jinja filtr pro datum a čas - aby se zobrazoval dobře a bez zbytečností

### ISSUE THREAD

**Issue by frenzymadness** [frenzymadness/donors_registry#119]
Datum a čas v Pythonu má v základu tvar `2019-11-11 11:34:20`, což není úplně český zápis a navíc může ještě obsahovat milisekundy, které jsou úplně k ničemu. Chtělo by to jednoduchou funkci registrovanou jako jinja filtr, který použijeme všude tam, kde se datum a čas ukazuje. Formát by mohl být: Den. Měsíc. Rok Hodiny:Minuty:Sekundy

Bacha ale na to, že takový formát může rozbít řazení v datatables tabulkách. I když to asi tolik nevadí, protože řadit se dá podle id, které je vždy správné a v korelaci s datem a časem. Ale bylo by fajn pro to najít řešení.

**Comment by JustScreaMy** [comment]
Zkusím si vzít

**Comment by encukou** [comment]
Nedávno jsem viděl jak kdosi psal o `data-order`, možná to pomůže?
https://datatables.net/manual/data/orthogonal-data#HTML-5
