### ISSUE TITLE
Testy

### ISSUE THREAD

**Issue by JustScreaMy** [frenzymadness/donors_registry#127]
Jestli jde tak nastavit linter testy ať kontrolují jen `/tests`  a `/registry` protože jinak se testy pouští i třeba na `/env` což zabere mockrát víc času

**Comment by frenzymadness** [comment]
Problém je, že když vyjmenujeme jen soubory a složky, které se mají testovat, tak do budoucna na něco jistě zapomeneme přidat. Lepší je mít složku s virtuálním prostředím mimo složku s projektem. Případně by se snad mělo dát zařídit, aby se nekontrolovaly všechny složky s tečkou na začátku názvu.

Koncifurace pro flake8 je ve .flake8 a pro isort je to .isort.cfg. Ideální by možná mohlo být, pokud by to šlo, ignorovat vše co je v .gitignore.

**Comment by frenzymadness** [comment]
pytest na to má plugin, ale nejsem si jistý, zda to stojí za to: https://github.com/tgs/pytest-gitignore

**Comment by JustScreaMy** [comment]
Dobře necháme to být tak jak to je.
