### ISSUE TITLE
Use Bootstrap Icons or unicode emoji ?

### ISSUE THREAD

**Issue by nappex** [frenzymadness/donors_registry#139]
For example use svg link of [Bootstrap Icon](https://icons.getbootstrap.com/):

```HTML
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
  <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
</svg>
```

**INSTEAD OF**

🗑

What do you think ?

Bootstrap Icon +1 🎉 
Unicode Emoji +1 🚀

**Comment by frenzymadness** [comment]
Could you please summarize the benefits and disadvantages of the two options? I don't have a strong opinion here but I also don't see a reason to change what we already use.

**Comment by nappex** [comment]
Emoji 
👎 is hard insert to code as image so its color and size is strict
👍 Looks always same and you don't download additional content from external server.

For example I think the bin emoji for to delete medal is very bad recognizable on red layout.

When I've used bootstrap icon
👍  it is as text so when I use button with hover effect it changes color. It is more customizable as text.
👍 I think there is more available choices of icons to action which we want to use/indent
👎 you download additional content from external server, but we are downloading css of bootstrap anyway  in our case. I have no idea if loading of our web app would take significantly more time with bootstrap icons. Maybe css bootstrap is not so time-consuming as Icons 🤷

**Comment by adelpopelkova** [comment]
Unless there are more users who have a problem with regular emojis, we won't implement this.
