### ISSUE TITLE
SQLAlchemy 2.0

### ISSUE THREAD

**Issue by JustScreaMy** [frenzymadness/donors_registry#144]
Jestli budeme přecházet na SQLAlchemy 2.0 až vyjde(nevím kdy a nevím jestli, ale je to dobré zmínit) tak již nebude možné využívat např `Medals.query.get(medal_id)`
https://docs.sqlalchemy.org/en/14/orm/query.html?highlight=query%20get#sqlalchemy.orm.Query.get
```
method sqlalchemy.orm.Query.get(ident)
Deprecated since version 1.4: The Query.get() method is considered legacy as of the 1.x series of SQLAlchemy and becomes a legacy construct in 2.0. The method is now available as Session.get() (Background on SQLAlchemy 2.0 at: Migrating to SQLAlchemy 2.0)
```
https://docs.sqlalchemy.org/en/14/changelog/migration_20.html

**Comment by frenzymadness** [comment]
Uvidíme také, kdy a jak budou kompatibilní další projekty - hlavně https://github.com/pallets/flask-sqlalchemy

**Comment by frenzymadness** [comment]
Opraveno v #192
