### ISSUE TITLE
Chybové stránky nebo flash messages na domovské stránce?

### ISSUE THREAD

**Issue by frenzymadness** [frenzymadness/donors_registry#152]
Při řešení #147 mě napadlo, že by místo samostatných stránek pro HTTP chyby jako 404 nebo 401 mohlo být lepší ukázat hlavní stránku a na ní jen flash message. Je to jednoduché na implementaci a mělo by to i řešit problém, že na stránce 401 se nedá jen tak ukázat přihlašovací formulář a uživatel musí přejít na domovskou stránku a přihlásit se tam.

**Comment by nappex** [comment]
souhlasím
