### ISSUE TITLE
Přesun titulů před křestní jméno

### ISSUE THREAD

**Issue by frenzymadness** [frenzymadness/donors_registry#178]
V importech se často stává, že tituly jako Bc nebo Ing jsou napsány za jménem, např.: `Lumír Balhar, Ing`. Bylo by super napsat chytristiku, která by je během importu přesunula před křestní jméno. Samozřejmě se to týká jen titulů, které se dávají před jméno. Tituly jako PhD. zůstávají za jménem.

**Comment by adelpopelkova** [comment]
Chtěla bych se zeptat, jak vypadá takový soubor, který se importuje?
```
rodné_číslo;Jméno;Příjmení,tituly;ulice_a_čp;město;pojišťovna;počet_darování
```
Jsou v tom souboru tituly umístěny u příjmení? A co by se mělo stát po importu, v případě, že by se titul měl přesunout před jméno? Měl by se přiřadit do sloupečku se jménem? Nebo se má stát něco jiného?

**Comment by frenzymadness** [comment]
Příklady souborů najdeš v testovacích datech, ale nejsou tam žádné tituly. Příklady sloupce s tituly ti pošlu v DM. Pokud se ve sloupci s příjmením najde titul, který patří před jméno, měl by se přesunout na začátek sloupce se jménem. Potíž je v tom, že některé tituly mají za jménem zůstat a může nastat i kombinace jako např.: Bc.,Dis. Asi bych na to použil reguláry a přesně definovaný seznam titulů, které patří před jméno. Testovací data pak můžeme udělat z aktuálních ostrých dat nějakou anonymizací.
