### ISSUE TITLE
Přidat další ocenění - Plaketa Dark krve - dar života

### ISSUE THREAD

**Issue by frenzymadness** [frenzymadness/donors_registry#34]
A při té příležitosti nejlépe nějak udělat to, aby se další přidání ocenění nemuselo dělat na tolika místech a napsat pro to třeba i nějaký ten test, který selže, když se to neudělá pořádně a všude.

**Comment by adelpopelkova** [comment]
Není tohle Issue téměř duplikátní s Issue https://github.com/frenzymadness/donors_registry/issues/22?

**Comment by frenzymadness** [comment]
Je :smile:
