### ISSUE TITLE
Přidat možnost jinde/manuální import

### ISSUE THREAD

**Issue by adelpopelkova** [frenzymadness/donors_registry#40]
U importu dat chybí „odběrné místo“ jinde / manuální import.

**Comment by frenzymadness** [comment]
Myslel jsem si, že když se nevybere žádné odběrné místo, tak to bude bráno jako manuální vklad odjinud, ale musím to zkontrolovat.

**Comment by frenzymadness** [comment]
A napsat na to test.

**Comment by adelpopelkova** [comment]
V základu se tam vybere Frýdek-Místek, takže tam není možnost nic nevybrat.
