### ISSUE TITLE
Session cookie expirace

### ISSUE THREAD

**Issue by frenzymadness** [frenzymadness/donors_registry#60]
Zdá se mi, že session cookie nemá žádnou expiraci a tak nikdy nedojde k automatickému odhlášení z důvod dlouhé neaktivity. Je třeba to ověřit a případně opravit. Klidně i s výjimkou pro vývojové prostředí.

**Comment by JustScreaMy** [comment]
Mohlo by se hodit
https://flask-login.readthedocs.io/en/latest/#cookie-settings

**Comment by frenzymadness** [comment]
Nejsem si tím jist, ale mám dojem, že "remember me" cookie je něco jiného než klasická session cookie. Remember me by mělo udržet přihlášení i při zavření prohlížeče. Zkusím se na to podívat více.
