### ISSUE TITLE
Nefunguje řazení dárců sloupci Darování a Ocenění

### ISSUE THREAD

**Issue by Glutexo** [frenzymadness/donors_registry#67]
`DataTables warning: table id=overview - list index out of range`

**Comment by JustScreaMy** [comment]
Jak tuhle chybu mohu reprodukovat?

**Comment by adelpopelkova** [comment]
> 
> 
> Jak tuhle chybu mohu reprodukovat?

Chyba nastane v tabulce s přehledem dárců po kliknutí na tlačítko seřazení sloupce Darování nebo Ocenění.

**Comment by JustScreaMy** [comment]
Přidávám info, potom hlásí stejnou hlášku i při překliknutí na jinou stránku přehledu dárců.

**Comment by frenzymadness** [comment]
Já bych skoro řekl, že v kombinaci s #125 bychom si mohli ten backend pro datatables napsat sami. Rozklíčovat to málo, co z toho JSON requestu potřebujeme, by snad nemuselo být tak složité a mohlo by to i zjednodušit implementaci na frontendu, protože se nebudeme muset přizpůsobovat fungování externího pluginu.

**Comment by adelpopelkova** [comment]
> Já bych skoro řekl, že v kombinaci s #125 bychom si mohli ten backend pro datatables napsat sami.

Vlastní datatables plugin bude potřeba asi i v https://github.com/frenzymadness/donors_registry/pull/111 - možná by stálo za to založit samostatné issue na ten plugin.
