### ISSUE TITLE
Umožnit dávku stáhnout jako soubor

### ISSUE THREAD

**Issue by frenzymadness** [frenzymadness/donors_registry#80]
Když už dávka projde našim importem a je opravená a filtrovaná, bylo by fajn mít možnost si ji stáhnout jako "CSV" soubor pro starý program, aby se tam dala bez práce už rovnou importovat.

**Comment by Glutexo** [comment]
Motivace je, že se bude paralelně provozovat i starý systém. Takže můžeme aspoň využít opravovacích schopností té naší nové i pro data do toho starého systému.
