### ISSUE TITLE
Rozšiř 404 na všechny GETy

### ISSUE THREAD

**Issue by Glutexo** [frenzymadness/donors_registry#87]
Viz https://github.com/frenzymadness/donors_registry/pull/69#discussion_r627352873.

Možná to Flask umí i nějak standardizovaně?

Pokračování #69.

**Comment by nappex** [comment]
> Viz [#69 (comment)](https://github.com/frenzymadness/donors_registry/pull/69#discussion_r627352873).
> 
> Možná to Flask umí i nějak standardizovaně?
> 
> Pokračování #69.

Vypadá to, že ne - jediný parametr je ident.

```python
 method sqlalchemy.orm.Query.get(ident)
 ```
 
 src: https://docs.sqlalchemy.org/en/14/orm/query.html?highlight=get#sqlalchemy.orm.Query.get
 
 Ani u této varianty nevidím možnost to handlovat:
 
 ```python
  method sqlalchemy.orm.Session.get(entity, ident, options=None, populate_existing=False, with_for_update=None, identity_token=None)
 ```
 
 src: https://docs.sqlalchemy.org/en/14/orm/session_api.html#sqlalchemy.orm.Session.get

**Comment by Glutexo** [comment]
Myslel jsem něco jako `@validates(RčInput)`. Dost možná na to existuje i nějaká flasčí knihovna. Ale to asi teď nepotřebujeme řešit. Tož růčo.

**Comment by Glutexo** [comment]
Používání nějakých entit/resources si nechme na jindy.
