### ISSUE TITLE
Pokud horní panel vyroste, překrývá obsah

### ISSUE THREAD

**Issue by Glutexo** [frenzymadness/donors_registry#96]
Je třeba upravit styl. Buď zařídit, ať se panel nerozvyšuje, nebo ať se obsah posouvá.

<img width="932" alt="Snímek obrazovky" src="https://user-images.githubusercontent.com/1161096/118403604-74ac3500-b66f-11eb-971d-9665465af6f4.png">

**Comment by j-jzk** [comment]
Chceme mít hlavní panel stále viditelný (přilepený k vrchu obrazovky)? Pokud ne, tak by mu šlo nastavit `position: static`. To by vyřešilo i to, že na úzké obrazovce se navigace rozleze přes polovinu výšky stránky a nejde skrýt.

**Comment by frenzymadness** [comment]
Jsem pro `position: static`, na mobilu jsem to ještě nikdy nezkusil, ale ten panel tam opravdu zavází a pokud to navíc vyřeší tento problém, tak proč ne.
